#!/usr/bin/env python3
import sys
import unicodedata

def get_ranges(predicate):
    ranges = []
    in_range = False
    start = 0
    for cp in range(0x110000):
        if predicate(cp):
            if not in_range:
                start = cp
                in_range = True
        else:
            if in_range:
                ranges.append((start, cp - 1))
                in_range = False
    if in_range:
        ranges.append((start, 0x10FFFF))
    return ranges

def is_whitespace(cp):
    # Rust regex \s matches White_Space property
    c = chr(cp)
    return c.isspace() or unicodedata.category(c) == 'Zs'

def is_letter(cp):
    return unicodedata.category(chr(cp)).startswith('L')

def is_mark(cp):
    return unicodedata.category(chr(cp)).startswith('M')

def is_number(cp):
    return unicodedata.category(chr(cp)).startswith('N')

def write_table(f, name, ranges):
    f.write(f"inline constexpr CodepointRange {name}[] = {{\n")
    for start, end in ranges:
        f.write(f"    {{0x{start:06X}, 0x{end:06X}}},\n")
    f.write("};\n\n")

def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "include/guild/runtime/unicode_tables.hpp"

    l_ranges = get_ranges(is_letter)
    m_ranges = get_ranges(is_mark)
    n_ranges = get_ranges(is_number)
    s_ranges = get_ranges(is_whitespace)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_unicode_tables.py. Do not edit directly.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")
        f.write("namespace guild::runtime::unicode {\n\n")
        f.write("struct CodepointRange {\n")
        f.write("    uint32_t first;\n")
        f.write("    uint32_t last;\n")
        f.write("};\n\n")

        write_table(f, "kLetterRanges", l_ranges)
        write_table(f, "kMarkRanges", m_ranges)
        write_table(f, "kNumberRanges", n_ranges)
        write_table(f, "kWhitespaceRanges", s_ranges)

        f.write("""
inline bool in_ranges(uint32_t cp, const CodepointRange* ranges, size_t count) {
    size_t low = 0;
    size_t high = count;
    while (low < high) {
        size_t mid = low + (high - low) / 2;
        if (ranges[mid].last < cp) {
            low = mid + 1;
        } else if (ranges[mid].first > cp) {
            high = mid;
        } else {
            return true;
        }
    }
    return false;
}

inline bool is_letter(uint32_t cp) {
    return in_ranges(cp, kLetterRanges, sizeof(kLetterRanges) / sizeof(kLetterRanges[0]));
}

inline bool is_mark(uint32_t cp) {
    return in_ranges(cp, kMarkRanges, sizeof(kMarkRanges) / sizeof(kMarkRanges[0]));
}

inline bool is_number(uint32_t cp) {
    return in_ranges(cp, kNumberRanges, sizeof(kNumberRanges) / sizeof(kNumberRanges[0]));
}

inline bool is_whitespace(uint32_t cp) {
    return in_ranges(cp, kWhitespaceRanges, sizeof(kWhitespaceRanges) / sizeof(kWhitespaceRanges[0]));
}

} // namespace guild::runtime::unicode
""")

if __name__ == "__main__":
    main()
